name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create .env file
        run: |
          echo "VITE_OCR_ENDPOINT=https://ocruteqparking-btbbfsgvezd4ehgn.eastus2-01.azurewebsites.net/api/detectar-placa?code=1gMd5punlgy-LER3wkMH7ghxX9MNeGsrSJLReBB2bS5KAzFunfP8dA==" >> .env
          echo "VITE_SUPABASE_URL=https://pzipoxrdfpqfairhuodg.supabase.co" >> .env
          echo "VITE_SUPABASE_PUBLISHABLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6aXBveHJkZnBxZmFpcmh1b2RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgwOTI0OTMsImV4cCI6MjEwMzY2ODQ5M30.YEChzqX82VZnzYTnrffM3pkqQb92RlGBVVjSzqU4OPE" >> .env

      - name: Deploy to Azure
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_DUNE_03D408810 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "build"
        env:
          VITE_OCR_ENDPOINT: "https://ocruteqparking-btbbfsgvezd4ehgn.eastus2-01.azurewebsites.net/api/detectar-placa?code=1gMd5punlgy-LER3wkMH7ghxX9MNeGsrSJLReBB2bS5KAzFunfP8dA=="
          VITE_SUPABASE_URL: "https://pzipoxrdfpqfairhuodg.supabase.co"
          VITE_SUPABASE_PUBLISHABLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6aXBveHJkZnBxZmFpcmh1b2RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgwOTI0OTMsImV4cCI6MjEwMzY2ODQ5M30.YEChzqX82VZnzYTnrffM3pkqQb92RlGBVVjSzqU4OPE"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_DUNE_03D408810 }}
          action: "close"
